[package]
name = "hdr2png"
version = "0.1.0"
edition = "2021"

[dependencies]
image = { version = "0.25.5", features = ["png", "hdr"] }
rgbe = "0.0.1"
clap = { version = "4.5.27", features = ["derive"] }

[[bin]]
name = "hdr2png"
path = "src/main.rs"
